import Head from 'next/head'
import { NextPageWithLayout } from '@customTypes/layouts'
import { ReactElement } from 'react'
import ClientLayout from '@layouts/clientLayout'

const Home : NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex h-screen justify-center items-center italic font-bold text-3xl'>
        <span className='animate-bounce text-blue-800'>Hello world!</span>
      </div>
    </>
  )
}

Home.getLayout = (page:ReactElement) => {
  return(
    <ClientLayout>{page}</ClientLayout>
  )
}

export default Home
